### PR TITLE
Home and About Page

### PR DESCRIPTION
**Pull request by kayode96-max**
the home page now has detailed step by step to help visitors use the website 
the about contains the overall overview of the app
on mobile the navbar shrinks to enhance display 
there are separate buttons for applicants and companies
image
 
image

### CODE REVIEW

**Comment by kayode96-max** [comment]
@Vedantjn 
This is what I have put together with my beginner knowledge 
I just hope it's good enough 
I get errors while trying to run build it's about MONGODB I think it's about server side authorization that's why vercel won't deploy

I'm open to corrections and comments 
Thanks for giving me the opportunity 
I'm almost through with the job management also by the way 
Same build error

**Comment by Vedantjn** [comment]
@kayode96-max Great work! Everything looks solid. One small thing I noticed: the heading and cards seem to have more margin on the right side than the left. Could you adjust them so that the margins are equal on both sides? Also, make sure it's responsive across different screen sizes. Thanks for your efforts

**Comment by kayode96-max** [comment]
Thanks @Vedantjn 
But please, what do you mean by updated repository I forked the code after the last commit

**Comment by Vedantjn** [comment]
Like there are multiple people working on this repo, and I keep on pergin the PRs, so do ensure whenever you are workin on your part, you are in sync with the main branch.

**Comment by kayode96-max** [comment]
Ok I get it now @Vedantjn 
I'm sorry If my questions are being much 😔
I'm trying to learn as fast as I can 

If I use the sync fork button in my forked branch that should update it but won't it delete my own commits

**Comment by Vedantjn** [comment]
No worries, @kayode96-max! Your questions are completely valid, and it's great that you're eager to learn! 😊
To keep your fork up to date without losing your work, follow these steps:

First, commit your local changes if you haven’t already.
Then, in your terminal, run these commands to update your fork.
git fetch upstream
git merge upstream/main
This will pull in the latest changes from the main branch into your fork without deleting your commits.

**Comment by kayode96-max** [comment]
Thank you very much @Vedantjn 
You're making this really interesting and fun for me and I'll like to see this become a complete success 
I'll work on the paddings and the navbar for other pages today

**Comment by kayode96-max** [comment]
Let me update the job management page and push that 1st

**Pull request closed without merging**
